# render.yaml
services:
  - type: web
    name: backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: your_database_url
      - key: JWT_SECRET_KEY
        value: your_jwt_secret
      - key: MAIL_USERNAME
        value: your_email@gmail.com
      - key: MAIL_PASSWORD
        value: your_app_password
      - key: FRONTEND_URL
        value: https://your-frontend.onrender.com
    buildFilter:
      paths:
        - backend/**

  - type: web
    name: frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    plan: free
    buildFilter:
      paths:
        - frontend/**
