"""Creates start and end time for a migration

Revision ID: 2a331fb6feab
Revises: ad1b5b74923c
Create Date: 2025-06-20 08:36:03.548228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a331fb6feab'
down_revision = 'ad1b5b74923c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.Numeric(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.create_index('idx_service_salon', ['salon_id', 'is_active'], unique=False)

    with op.batch_alter_table('stylists', schema=None) as batch_op:
        batch_op.alter_column('specialization',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.create_index('idx_stylist_salon', ['salon_id', 'is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stylists', schema=None) as batch_op:
        batch_op.drop_index('idx_stylist_salon')
        batch_op.alter_column('specialization',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index('idx_service_salon')
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.Numeric(precision=10, scale=2),
               type_=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
