"""Creates start and end time for a migration

Revision ID: ad1b5b74923c
Revises: 9f8749bdaa2c
Create Date: 2025-06-20 08:16:16.180817

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad1b5b74923c'
down_revision = '9f8749bdaa2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DateTime(), nullable=False))
        batch_op.alter_column('end_time',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_index(batch_op.f('idx_appointment_datetime'))
        batch_op.create_index('idx_stylist_time', ['stylist_id', 'start_time'], unique=True)
        batch_op.drop_column('appointment_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_date', sa.DATETIME(), nullable=False))
        batch_op.drop_index('idx_stylist_time')
        batch_op.create_index(batch_op.f('idx_appointment_datetime'), ['stylist_id', 'appointment_date'], unique=1)
        batch_op.alter_column('end_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('start_time')

    # ### end Alembic commands ###
