"""fix_user_stylist_relationships

Revision ID: 317fbf472ddf
Revises: 584a8699f62d
Create Date: 2025-06-28 15:35:22.821539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317fbf472ddf'
down_revision = '584a8699f62d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_users_stylist_id'), type_='foreignkey')
        batch_op.create_foreign_key('fk_users_stylist_id', 'stylists', ['stylist_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_users_stylist_id'), 'stylists', ['stylist_id'], ['id'], initially='DEFERRED', deferrable=True)

    # ### end Alembic commands ###
