"""Creates start and end time for a migrationd

Revision ID: 37de6bdcf1f3
Revises: 2a331fb6feab
Create Date: 2025-06-20 08:43:36.845430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37de6bdcf1f3'
down_revision = '2a331fb6feab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('appointment_date', sa.DateTime(), nullable=False))
        batch_op.alter_column('end_time',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_stylist_time'))
        batch_op.create_index('idx_appointment_datetime', ['stylist_id', 'appointment_date'], unique=True)
        batch_op.drop_column('start_time')

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('price',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Float(),
               nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_service_salon'))
        batch_op.drop_column('created_at')

    with op.batch_alter_table('stylists', schema=None) as batch_op:
        batch_op.alter_column('specialization',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_index(batch_op.f('idx_stylist_salon'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stylists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_stylist_salon'), ['salon_id', 'is_active'], unique=False)
        batch_op.alter_column('specialization',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DATETIME(), nullable=True))
        batch_op.create_index(batch_op.f('idx_service_salon'), ['salon_id', 'is_active'], unique=False)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('price',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('duration',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('start_time', sa.DATETIME(), nullable=False))
        batch_op.drop_index('idx_appointment_datetime')
        batch_op.create_index(batch_op.f('idx_stylist_time'), ['stylist_id', 'start_time'], unique=1)
        batch_op.alter_column('end_time',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.drop_column('appointment_date')

    # ### end Alembic commands ###
