"""Adss stylist id to users

Revision ID: 500f62faeb41
Revises: b99858937080
Create Date: 2025-06-28 10:38:44.509732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500f62faeb41'
down_revision = 'b99858937080'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stylists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stylist_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
        'fk_users_stylist_id',  # <- this is the required name
        'stylists',
        ['stylist_id'],
        ['id']
    )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stylists', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('stylist_id')

    # ### end Alembic commands ###
