"""Adss stylist id to userdddds

Revision ID: 584a8699f62d
Revises: 500f62faeb41
Create Date: 2025-06-28 10:58:29.932792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '584a8699f62d'
down_revision = '500f62faeb41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stylist_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
        'fk_users_stylist_id',  # <-- give it a name here
        'stylists',
        ['stylist_id'],
        ['id'],
        use_alter=True,
        deferrable=True,
        initially='DEFERRED'
    )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('stylist_id')

    # ### end Alembic commands ###
